### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Mrunknow3** [SaurabhKaperwan/CSX#12]
Can you add subtitles in vadapav extension.

**Comment by SaurabhKaperwan** [comment]
If the video source has subtitles it will show or you can try online subtitles

**Comment by SaurabhKaperwan** [comment]
Is this website good : https://pikahd.com/

**Comment by Mrunknow3** [comment]
I never used 

But people say :
https://nxprime.in/page/2.html
https://toonworld4all.me/


That's good

**Comment by SaurabhKaperwan** [comment]
Added PikaHD (Hindi dubbed) inside of Katmovie extension
