### ISSUE TITLE
Cinestream Issue

### ISSUE THREAD

**Issue by Politecoder** [SaurabhKaperwan/CSX#127]
![Screenshot_2024-11-09-17-38-16-289](https://github.com/user-attachments/assets/0098ba63-08ad-4d2e-b1b7-cb54fe5478a9)
There are 6 episodes, why are they not getting updated on cinestream ?

**Comment by Politecoder** [comment]
![Screenshot_2024-11-09-17-42-17-847](https://github.com/user-attachments/assets/e65a4011-681a-4ca5-9e20-6f6c98ef5dfb)
In TMDB all were updated on the date of release

**Comment by SaurabhKaperwan** [comment]
Use search
