### ISSUE TITLE
Vega movies

### ISSUE THREAD

**Issue by Mrunknow3** [SaurabhKaperwan/CSX#13]
Vega movies and lux work sometimes but most of the time they don't work. 

This time Vega movie series works in 480p, 720p, but 1080p doesn't work.

**Comment by SaurabhKaperwan** [comment]
Delete streamplay extension from phisher repo then it will work

**Comment by Mrunknow3** [comment]
![IMG_20240702_151004.jpg](https://github.com/SaurabhKaperwan/CSX/assets/154901963/db974eed-8a99-47e2-852c-ab9dcd2333e2)

Lux movie

**Comment by SaurabhKaperwan** [comment]
Working well for me . use dns or vpn

**Comment by Mrunknow3** [comment]
Vega movies do the same but after we click any series.

**Comment by Mrunknow3** [comment]
How to use vpn Or dns in tv

**Comment by SaurabhKaperwan** [comment]
It is your isp issue or weak internet speed

**Comment by SaurabhKaperwan** [comment]
I don't use tv so I don't know

**Comment by Mrunknow3** [comment]
> It is your isp issue or weak internet speed

I have wifi
