### ISSUE TITLE
Check

### ISSUE THREAD

**Issue by Mrunknow3** [SaurabhKaperwan/CSX#14]
Can you check vegamovies, stranger Things S1E1-1080p and money hiest s1e1-1080p. 
Works or not

**Comment by SaurabhKaperwan** [comment]
I will look into it

**Comment by SaurabhKaperwan** [comment]
Now it should works

**Comment by Mrunknow3** [comment]
Now money hiest working, but stranger Things provider we can see but that does not load and say no links found in 1080p.

**Comment by SaurabhKaperwan** [comment]
Because it only has a download only link to therefore you can't stream it

**Comment by Mrunknow3** [comment]
Arigatl gozaimusu
