### ISSUE TITLE
Request to Add

### ISSUE THREAD

**Issue by Zafor7869** [SaurabhKaperwan/CSX#142]
https://onlykdrama.online/

![Screenshot_20241130_154318](https://github.com/user-attachments/assets/caa5c725-3d19-4eb2-ad02-8cf5ad5c9660)

In this website has available lots of Korean dramas with good qualities and dub. Please brother add this if possible. It's a humble request.

**Comment by SaurabhKaperwan** [comment]
No it has cloudflare protection
