### ISSUE TITLE
Please add this sites 🙏

### ISSUE THREAD

**Issue by Kira0116** [SaurabhKaperwan/CSX#15]
• https://trooporiginals.xyz/ - Hd and Multi Provider 

• https://bromovies.co/ - All Indian languages provider with Frequent updates

**Comment by Kira0116** [comment]
Any reply?? 🙄

**Comment by SaurabhKaperwan** [comment]
If I have time I will add bromovies

**Comment by SaurabhKaperwan** [comment]
Added 0gomovies (bromovies is mirror of 0gomovies)

**Comment by Kira0116** [comment]
> Added 0gomovies (bromovies is mirror of 0gomovies)

Bro can you please add Telugu section and multi language section here 🙏🙏😭 please bro this is my final request
![Uploading Screenshot_2024-07-26-08-44-16-767_com.lagradost.cloudstream3.prerelease.jpg…]()

**Comment by SaurabhKaperwan** [comment]
Screenshot is not showing

**Comment by SaurabhKaperwan** [comment]
Again send screenshot

**Comment by Kira0116** [comment]
![Uploading Screenshot_2024-07-26-08-44-16-767_com.lagradost.cloudstream3.prerelease.jpg…]()
![Uploading Screenshot_2024-07-26-08-44-16-767_com.lagradost.cloudstream3.prerelease.jpg…]()

**Comment by Kira0116** [comment]
> Again send screenshot 

![Screenshot_2024-07-26-08-44-16-767_com.lagradost.cloudstream3.prerelease.jpg](https://github.com/user-attachments/assets/056eed32-168d-41c1-826d-236a1f0a1dd6)

**Comment by SaurabhKaperwan** [comment]
> > Again send screenshot 
> 
> ![Screenshot_2024-07-26-08-44-16-767_com.lagradost.cloudstream3.prerelease.jpg](https://github.com/user-attachments/assets/056eed32-168d-41c1-826d-236a1f0a1dd6)
> 
> 

I'm talking about link error

**Comment by Kira0116** [comment]
> > > Again send screenshot 
> > 
> > ![Screenshot_2024-07-26-08-44-16-767_com.lagradost.cloudstream3.prerelease.jpg](https://github.com/user-attachments/assets/056eed32-168d-41c1-826d-236a1f0a1dd6)
> > 
> > 
> 
> I'm talking about link error

![Screenshot_2024-07-26-09-45-29-832_com.lagradost.cloudstream3.prerelease.jpg](https://github.com/user-attachments/assets/1d46ba8f-1858-421e-ace4-0fd9b66bede2)

![Screenshot_2024-07-26-09-45-34-558_com.lagradost.cloudstream3.prerelease.jpg](https://github.com/user-attachments/assets/6925c50a-df76-416b-abaf-d1c9f40db68e)

**Comment by SaurabhKaperwan** [comment]
Working for me.
![Screenshot_2024-07-26-09-50-10-24_cfa2fd239c8cded9285432912d0e0818.jpg](https://github.com/user-attachments/assets/53d952db-2b6c-43a1-bb22-a112788890cb)

**Comment by SaurabhKaperwan** [comment]
Are you using the pre-release version of app

**Comment by Kira0116** [comment]
> Are you using the pre-release version of app

It worked with VPN 🙂👍 I'm using pre-release app.
Please look into sections i mentioned too. Thanks
