### ISSUE TITLE
Issue of these sources 

### ISSUE THREAD

**Issue by Krishna-art-dev** [SaurabhKaperwan/CSX#16]
Cinevez ( ok )
Full4movies ( no link found )
Katmovies ( no link found )
Pikahd ( no link found )
Moviesdrive (ok )
Online movie Hindi ( connection timeout)
Vadapav ( ok )
Vegamovies ( no link found )
Lux movies ( no link found)

Please fix these thanks 
@SaurabhKaperwan

**Comment by SaurabhKaperwan** [comment]
Vegamovies, luxmovies are working fine if not working then uninstall streamplay extension

**Comment by SaurabhKaperwan** [comment]
For online movie Hindi use vpn

**Comment by SaurabhKaperwan** [comment]
And I will fix full4movies and katmovie later

**Comment by SaurabhKaperwan** [comment]
Fixed full4movies

**Comment by Krishna-art-dev** [comment]
> Vegamovies, luxmovies are working fine if not working then uninstall streamplay extension

Why streamplay extension? It's different plugin na? And of different creater?

**Comment by SaurabhKaperwan** [comment]
Ya it is a bug in cloudstream . streamplay also have vega which is outdated and every time it is calling streamplay vega

**Comment by SaurabhKaperwan** [comment]
If u want to use both then u have to install my extension before then streamplay.
