### ISSUE TITLE
Site Request 

### ISSUE THREAD

**Issue by Chani-rajat** [SaurabhKaperwan/CSX#17]
Provider plz add this website.
It's the best web with no ads 
https://cinemaluxe.live/
Plz reply....

**Comment by SaurabhKaperwan** [comment]
Can't add due to cloudflare protection

**Comment by Chani-rajat** [comment]
Provider 
I think cloudfare protection is now
Removed 
Plz add that website

**Comment by SaurabhKaperwan** [comment]
Added this website.

**Comment by Chani-rajat** [comment]
Not working 😞 
(No links found)

**Comment by Chani-rajat** [comment]
I reported it on Telegram
