### ISSUE TITLE
NSFW Sites

### ISSUE THREAD

**Issue by ChristianWaits** [SaurabhKaperwan/CSX#19]
If I'm not mistaken, this Repo used to have Porntrex and a couple of other NSFW plugins. But now they are not showing anymore. Did you move them to another Repo? or how can we install them now? Thank you very much.

**Comment by SaurabhKaperwan** [comment]
Install this:
https://raw.githubusercontent.com/phisher98/CXXX/builds/CXXX.json

**Comment by SaurabhKaperwan** [comment]
I will add this in cxxx repo

**Comment by ChristianWaits** [comment]
Thank you very much. I will install Porntrex from CXXX then, when it's available. Keep up the good work, thanks!

**Comment by SaurabhKaperwan** [comment]
Added porntrex and 3 new nsfw extensions in cxxx repo.

**Comment by ChristianWaits** [comment]
Fantastic! I've just installed them. Thank you so much.
