### ISSUE TITLE
Moviedrive and vega movies issue

### ISSUE THREAD

**Issue by Mrunknow3** [SaurabhKaperwan/CSX#20]
Moviedrive stranger Things season (1-3) coming soon issue

Vegamovies search doesn't working

**Comment by adilurrhmn** [comment]
Luxmovies - streaming in only 480p..... 720p, 1080p , not even showing

**Comment by SaurabhKaperwan** [comment]
> Luxmovies - streaming in only 480p..... 720p, 1080p , not even showing 

Show example.

**Comment by Mrunknow3** [comment]
Vegamovies searching fixed.

**Comment by SaurabhKaperwan** [comment]
> Vegamovies searching fixed. 

Ya I fixed it.

**Comment by Mrunknow3** [comment]
Waiting for moviedrive.

**Comment by Mrunknow3** [comment]
@Surendrajat bro season (1-2) fixed and I'm watching season 3, that says coming soon.

**Comment by SaurabhKaperwan** [comment]
> @Surendrajat bro season (1-2) fixed and I'm watching season 3, that says coming soon. 

I can fix it but i will not fix this because I can't fix every single case u can use other extensions.

**Comment by Mrunknow3** [comment]
Any recommendation 
I want hindi dub
1080p
Eng subtitles
Low buffering
No vpn

Multimovie : so much buffering every 10sec

Vega movie: not working without vpn and only vidhide working

Hdmovie2 : not subtitles

Vadapav: doesn't work. 

Ik some of souce doesn't you but I just want to recommend it for stranger Things s3.

**Comment by SaurabhKaperwan** [comment]
> Any recommendation 
> I want hindi dub
> 1080p
> Eng subtitles
> Low buffering
> No vpn
> 
> Multimovie : so much buffering every 10sec
> 
> Vega movie: not working without vpn and only vidhide working
> 
> Hdmovie2 : not subtitles
> 
> Vadapav: doesn't work. 
> 
> Ik some of souce doesn't you but I just want to recommend it for stranger Things s3. 

Vegamovies is working fine without vpn. Phisher and I have multiple extensions.

**Comment by SaurabhKaperwan** [comment]
![Screenshot_2024-07-20-12-39-22-16_cfa2fd239c8cded9285432912d0e0818.jpg](https://github.com/user-attachments/assets/661ab05c-1271-4a79-9a64-6cfd4c8ef950)

**Comment by SaurabhKaperwan** [comment]
Vadapav working fine

**Comment by Mrunknow3** [comment]
Vegamovies source you see but only work was vidhide  other source just buffering.

**Comment by SaurabhKaperwan** [comment]
All sources working fine for me in vegamovies I think it is ur network issue.

**Comment by Mrunknow3** [comment]
Oke

**Comment by adilurrhmn** [comment]
> > Luxmovies - streaming in only 480p..... 720p, 1080p , not even showing
> 
> Show example.

![Screenshot_2024-07-20-17-53-40-19_cfa2fd239c8cded9285432912d0e0818](https://github.com/user-attachments/assets/230e8b7a-43a7-4a1e-942d-10d2c9915fc6)

**Comment by SaurabhKaperwan** [comment]
Which movie?

**Comment by adilurrhmn** [comment]
All movies are playing in 480p only

**Comment by adilurrhmn** [comment]
Tried playing different different movies but same issue

**Comment by adilurrhmn** [comment]
https://github.com/user-attachments/assets/3b622eb9-5534-4250-9548-11094ee14325

**Comment by adilurrhmn** [comment]
> VID_20240720180211.mp4


https://github.com/user-attachments/assets/925de014-c45f-4a66-b55d-d7d49382ecc3

**Comment by SaurabhKaperwan** [comment]
I think this issue is related to the slowness of the website because sometimes it is working fine for me and sometimes not.

**Comment by SaurabhKaperwan** [comment]
Are u clicking on the skip loading button?

**Comment by adilurrhmn** [comment]
> Are u clicking on the skip loading button?

Yes

**Comment by SaurabhKaperwan** [comment]
> > Are u clicking on the skip loading button?
> 
> Yes

Then how u are going to get all the links if u click skip loading.

**Comment by adilurrhmn** [comment]
If I don't click on the skip button then its not loading, showing black screen. That's why I clicked the button

**Comment by adilurrhmn** [comment]
See. Only loading screen 
![Screenshot_2024-07-20-21-40-36-02_cfa2fd239c8cded9285432912d0e0818](https://github.com/user-attachments/assets/7da2facb-db9c-4a01-ab6a-94bd244aa25c)

**Comment by adilurrhmn** [comment]
And one thing, 
After clicking skip button in the other sites is working smoothly in 1080p but it doesn't work in luxmovies

**Comment by SaurabhKaperwan** [comment]
Bhai jada dimaag mt lga bs skip wala button mt dba

**Comment by adilurrhmn** [comment]
Nahi dabane se kuch nahi ata .... Loading show ho raha hai....

**Comment by adilurrhmn** [comment]
Okay... Bro no problem.. dusra site use kar lenge..
