### ISSUE TITLE
Extension Fix 

### ISSUE THREAD

**Issue by ShankarKSH001** [SaurabhKaperwan/CSX#24]
Can you fix MassTamilanProvider, LikDev-256 already created extension for this but it not working now.

Link : https://github.com/LikDev-256/likdev256-tamil-providers/tree/2e6b7d1332e2380332ef29ee2ff9a1cc6f816dfa/MassTamilanProvider

It shows:
![Screenshot_20240707-155632](https://github.com/user-attachments/assets/be3ffe12-0f4d-408a-a9e7-d2130ffb929b)

**Comment by SaurabhKaperwan** [comment]
Sorry but I don't make music providers

**Comment by ShankarKSH001** [comment]
Can you try to fix it  if possible.

**Comment by SaurabhKaperwan** [comment]
No because it is a waste of time u can use other music apps.

**Comment by ShankarKSH001** [comment]
> No because it is a waste of time u can use other music apps.

Bro this site has quality music that's why I request  you to fix this site if you try you also love this site .

**Comment by ShankarKSH001** [comment]
Hello bro pls try to fix this I think it's not big deal for you cause it's working with vlc.
