### ISSUE TITLE
Netflix mirror

### ISSUE THREAD

**Issue by Mrunknow3** [SaurabhKaperwan/CSX#25]
Netflix mirror was a near to perfect website I appreciate that too much. 

But if you add subtitles that was a perfect Netflix mirror.

**Comment by SaurabhKaperwan** [comment]
If the website doesn't have subtitles then how am I going to add it. Just use online subtitles.

**Comment by Mrunknow3** [comment]
I thanked that Netflix mirror like Yomiroll but that's not true? 

You know any crunchyroll mirror like yomiroll,
