### ISSUE TITLE
Problem with vegamovies and luxmovies

### ISSUE THREAD

**Issue by aneesh1122** [SaurabhKaperwan/CSX#28]
Not able to search anything in vega and luxmovies. I can only see content which are in homepage

**Comment by SaurabhKaperwan** [comment]
Vegamovies search is working and in luxmovies they raise cloudflare so can't fix it.

**Comment by aneesh1122** [comment]
Yeah vega is working fine. For some reason it wasn't working back then. Maybe because of my internet.
