### ISSUE TITLE
Vegamovies and LuxMovies subtitle issue

### ISSUE THREAD

**Issue by Rayforest** [SaurabhKaperwan/CSX#3]
Wow! This repo is great!!! Especially LuxMovies, Vegamovies and Cinevez. You did a brilliant job! Much love ❤️

So there is this issue with vegamovies subtitles. Been there for quite sometime, I guess. Was also present on Sora as well as Codestream. The preloaded subtitle breaks at random points. What I mean by this is that the subtitle appears for a few seconds and then disappear. Then after a short while it reappears. And it goes on. You might have already noticed this on vegamovies

One way to solve this is to download a subtitle from online. Also on Codestream since there are usually more than one subtitle, selecting another one could solve this issue. I guess the subtitle only has this issue when we choose the subtitle that comes preloaded. It only becomes a problem when there is no subtitle online.

For example, I tried to watch the movie '8 A.M. Metro' on LuxMovies (same issue with Codestream). There is one subtitle, but it breaks off here and there. And I can't load a subtitle from Internet because it is not to be found anywhere, sadly. 

I think, most likely this issue is not fixable. But anyways, thank you for this and your repo ✨

**Comment by SaurabhKaperwan** [comment]
You can report this issue in the cloudstream app repo

**Comment by Rayforest** [comment]
> You can report this issue in the cloudstream app

I guess subtitle breaking issue has already been reported. I just thought maybe this issue was specific to vegamovies. No worries, all good 😍🥰
