### ISSUE TITLE
bug report there is no option to view more than 20 episode

### ISSUE THREAD

**Issue by dinkusoni** [SaurabhKaperwan/CSX#31]
![Screenshot_2024-08-03-09-56-53-30_cfa2fd239c8cded9285432912d0e0818.jpg](https://github.com/user-attachments/assets/76680440-d271-4f52-a39b-9bb65c053cda)

![Screenshot_2024-08-03-09-56-59-41_cfa2fd239c8cded9285432912d0e0818.jpg](https://github.com/user-attachments/assets/d36fa284-d9a7-407d-a054-02dd24aff762)

**Comment by Mrunknow3** [comment]
@SaurabhKaperwan you know who repo was the second Netflix mirror that second Netflix mirror ke wajah se tumhara Netflix mirror work nhi kr rha

**Comment by Mrunknow3** [comment]
@SaurabhKaperwan you know who repo was the second Netflix mirror that second Netflix mirror ke wajah se tumhara Netflix mirror work nhi kr rha

**Comment by SaurabhKaperwan** [comment]
> @SaurabhKaperwan you know who repo was the second Netflix mirror that second Netflix mirror ke wajah se tumhara Netflix mirror work nhi kr rha

What are u saying?

**Comment by Mrunknow3** [comment]
![IMG_20240806_132847.jpg](https://github.com/user-attachments/assets/43544d05-5545-4968-a40a-ca44bf304b62)

Here 2 Netflix mirror second wala kiska h

**Comment by Mrunknow3** [comment]
![IMG_20240806_133022.jpg](https://github.com/user-attachments/assets/e695d911-8a70-43e9-bb58-2772f61f0ffa)

Netflix mirror

**Comment by SaurabhKaperwan** [comment]
I don't know

**Comment by SaurabhKaperwan** [comment]
Maybe horis repo

**Comment by dinkusoni** [comment]
> > @SaurabhKaperwan you know who repo was the second Netflix mirror that second Netflix mirror ke wajah se tumhara Netflix mirror work nhi kr rha
> 
> What are u saying? 

🤣 🤣
