### ISSUE TITLE
Site Request In Repo

### ISSUE THREAD

**Issue by Moviellect** [SaurabhKaperwan/CSX#33]
Today I checked two different **vegamovies** websites.

**First** with this UI and **not** support _online video play_:- 

![Screenshot_2024-08-05-08-15-25-68](https://github.com/user-attachments/assets/8db28f0a-c949-4ab9-be55-2a2fc9bfa26d)

![Screenshot_2024-08-05-08-15-38-70](https://github.com/user-attachments/assets/244486f9-7f92-4aee-8cda-e2b4f52a93a9)

-----------------------------------------------------------------------

**Second** with this UI and support _online video play_ with **multiple quality**:-

![Screenshot_2024-08-05-08-10-08-21](https://github.com/user-attachments/assets/e8635fdc-328d-47c6-b697-6bebf0b7116c)

![Screenshot_2024-08-05-08-10-28-18](https://github.com/user-attachments/assets/be416d85-f4fd-48ac-9631-ca6232c099dc)

Please add this website in repository🥺

**Comment by SaurabhKaperwan** [comment]
Not going to add

**Comment by Moviellect** [comment]
Why sir.

**Comment by SaurabhKaperwan** [comment]
it is not worth the effort to add that fake vega website
