### ISSUE TITLE
Request 

### ISSUE THREAD

**Issue by Kira0116** [SaurabhKaperwan/CSX#38]
• **https://telugumv.xyz/**
Bro, could you please add this site? It offers a wide range of content including 4k movies. I'm referring to short links, not vidhide servers. If there's any possible way to bypass those links, I would greatly appreciate it if you could add this site. 🙏 😞

Also Please replace Uhd movies with ola movies it has more multi Content
• **https://olamovies.rent/**

**Comment by SaurabhKaperwan** [comment]
Not going to add telgu Website because it have very less content
