### ISSUE TITLE
Moviesmod not working

### ISSUE THREAD

**Issue by salman731** [SaurabhKaperwan/CSX#39]
Please look into this. I have tested it without vpn

![Screenshot_20240811_123640 1](https://github.com/user-attachments/assets/2e54572e-fc0b-4751-bab6-3f85f3e3feca)

**Comment by SaurabhKaperwan** [comment]
Use vlc

**Comment by salman731** [comment]
Will all links work with vlc player?
Will they work other than vlc player?
