### ISSUE TITLE
Fix sources 

### ISSUE THREAD

**Issue by Krishna-art-dev** [SaurabhKaperwan/CSX#40]
•0gomovies = no link found 
•Anytime = works 
•Cinemulex = no link found
•Cinevez = works
•Full4movies = no link found
•Katmovieshd = cloudflare protection ( can't we able to bypass this with manual verification just like aniyomi does? ) 
•Pika hd = no link found 
•Moviesdrive = works
•Moviesmod = takes hell lot of internet ( probably because it's a downloading site) 
     • tell me what instan ( download ) am assuming it's from downloading using cs3
   • resumebot server have vlc written. For using in vlc thorough cs3?
    • and cf worker what with it? Normal streaming or this is also a downloading one. It loads fast then both above 2 but it also uses hell lot of internet 
   >( Also at first I thought servers doesn't works, and took a lot of internet, after a lot of patience it loads all three of them, is there any way to make it faster and takes less internet, like internet speed was ~25mb/s and it took like more then 1 min to load, instant and resume bot, more then 30sec to cf worker, if need speed is slow normal person would think this source doesn't work 😐 and it's my fav site so please do something about it if you can, like uhd movies cf worker is quite fast, and movies mod in streamplay also, I can't able to compare both 2, that's why am asking you to check it thanks )>
Topmovies = same as moviesmod 
     >• gonna use this 2 to download when have fast internet 😂 also tell me, this instant download from cs3 will be quite fast na? >

•Netflix mirror = working 
•Online movies Hindi = connection timeout 
•Vadapav= working 
•Vegamovies = working op
•Luxmovies = working 
•World4ufree = working 

Why didn't you add animeflix of moviesmod? It's the same
If will have any recommendations will share below 

Thanks

**Comment by SaurabhKaperwan** [comment]
Only katmovie, pika and cinemaluxe are not working all other extensions working fine

**Comment by Krishna-art-dev** [comment]
> Only katmovie, pika and cinemaluxe are not working all other extensions working fine

Hn just checked all extensions, as I had done previously also, and had questions so asked, please can you ans that?

**Comment by SaurabhKaperwan** [comment]
Instant download links are only for downloading u can't stream it in cs3 u can stream in vlc but it takes a lot of internet and are non seekable video

**Comment by SaurabhKaperwan** [comment]
For resume vlc links will work on any player or downloader but it does not work in cs3 because of timeout out in cs3

**Comment by Krishna-art-dev** [comment]
> For resume vlc links will work on any player or downloader but it does not work in cs3 because of timeout out in cs3

What about resumebot and cf worker?

**Comment by SaurabhKaperwan** [comment]
Most of the time they work in cs3 but sometimes it also has  timeout problem in cs3 then u have to use vlc

**Comment by Krishna-art-dev** [comment]
> Most of the time they work in cs3 but sometimes it also has timeout problem in cs3 then u have to use vlc

And if I doesnt stream it and download directly from cs3? What about it?

**Comment by SaurabhKaperwan** [comment]
Cs3 download is not good and slow like u can't download instant link it will download indefinitely

**Comment by Krishna-art-dev** [comment]
> Cs3 download is not good and slow like u can't download instant link it will download indefinitely

Then the most optimal use will be to, copy it's direct link and download it using browser

**Comment by Krishna-art-dev** [comment]
😐 cs3 have play in browser, direct play in browser and it downloads it because it's isn't in streaming format, thanks, it gonna help me to download movies faster without ads

**Comment by Krishna-art-dev** [comment]
And did you remove download that was written in vega movies sources? Please keep that written also that way people will gonna help, like pixeldrain server is for streaming, and v-cloud streams well and fast server downloading is fast too

**Comment by SaurabhKaperwan** [comment]
I did not do anything I think the website changed something
