### ISSUE TITLE
REQUEST

### ISSUE THREAD

**Issue by Politecoder** [SaurabhKaperwan/CSX#44]
https://filmycity.blog/
Please check this site it has all direct links and no extra efforts required, hope you find this usefull.
Thanks

**Comment by Politecoder** [comment]
I updated the url

**Comment by Politecoder** [comment]
Please do confirm if this site is suitable to add or not, it was my last request rest thanks for the plugins

**Comment by Politecoder** [comment]
Any response ?

**Comment by SaurabhKaperwan** [comment]
It depends on my mood and if I have free time or not

**Comment by Politecoder** [comment]
No problem, but please do check this site it's very simple and great

**Comment by SaurabhKaperwan** [comment]
Ok

**Comment by SaurabhKaperwan** [comment]
Not going to add this website
