### ISSUE TITLE
Collection wanted to share, check if you have time, leave if you don't want to.

### ISSUE THREAD

**Issue by Rachitidk** [SaurabhKaperwan/CSX#45]
**Almost none of them require anykind of bypass, and max don't have cloudflare protection**
1. https://hydrahd.com
> Multiserver
2. https://yassflix.live
> Multiserver, Personal favourite
3. https://x265rips.xyz
> Simple, direct tg and drive link
4. https://toonhub4u.net
> Anime, Cartoon
5. https://www.vidbinge.com
> Multiserver
6. https://www.tvids.tv
> Multiserver
7. https://nunflix.com
> Multiserver
8. https://rivestream.live
> Multiserver
9. https://1moviesfd.fun
> Simple
10. https://mkvmoviespoint.kim
> Simple
11. https://animerulz.pro
> Anime
12. https://animesakura.co
> Direct Google drive link, also present in aniyomi
13. https://www.rgshows.me
> Multiserver, option for language selection
14. https://novastream.top
> Multiserver
15. https://upmovies.net
> Simple, too many source

**Comment by Mrunknow3** [comment]
Anime dekho and up movies already exist in cs3

**Comment by SaurabhKaperwan** [comment]
Next time make a request for a single website at a time
