### ISSUE TITLE
extension issue

### ISSUE THREAD

**Issue by Mrunknow3** [SaurabhKaperwan/CSX#49]
You add a new extension deadstream in Deadstream ultimate spider man has all india lang and subs, but in your extension only have the english language and not sub with the same server.

**Comment by SaurabhKaperwan** [comment]
Before making an issue check the extension properly it has dual audio

**Comment by Mrunknow3** [comment]
![Screenshot_2024-08-28-14-00-25-034_com.lagradost.cloudstream3.prerelease.jpg](https://github.com/user-attachments/assets/7e2a288e-cf8b-4bd5-ba6d-145173631731)

![Screenshot_2024-08-28-14-00-28-391_com.lagradost.cloudstream3.prerelease.jpg](https://github.com/user-attachments/assets/1a8019a6-4f43-44ac-9a14-a4b85c10e6df)

**Comment by SaurabhKaperwan** [comment]
Play source which doesn't have quality

**Comment by Mrunknow3** [comment]
Now working
