### ISSUE TITLE
Wrong Information 

### ISSUE THREAD

**Issue by adilurrhmn** [SaurabhKaperwan/CSX#5]
Instead of Quality, It's showing Season in Vegamovies and luxmovies.
Please Fix it. 
![Screenshot_2024-06-12-20-34-32-71_cfa2fd239c8cded9285432912d0e0818](https://github.com/SaurabhKaperwan/CSX/assets/124466769/b70f4f18-8b5a-4e6b-b774-2fefda0b9eb6)

**Comment by SaurabhKaperwan** [comment]
Fixed your issue

**Comment by adilurrhmn** [comment]
That issue is now fixed but still no link found in luxmovies and Vegamovies

**Comment by SaurabhKaperwan** [comment]
> That issue is fixed now but still no link found in luxmovies and Vegamovies 

That is because they raised cloudflare protection but they will remove cloudflare protection after some time I hope
