### ISSUE TITLE
Fix

### ISSUE THREAD

**Issue by Chani-rajat** [SaurabhKaperwan/CSX#52]
The Netflix Mirror repo is not working 
Plz fix that 😊
![Screenshot_20240903-214311](https://github.com/user-attachments/assets/b317385b-5bb2-4f96-b6d5-7efbbd8a66dc)

**Comment by SaurabhKaperwan** [comment]
Can't fix they raised human verification protection

**Comment by Chani-rajat** [comment]
Okay
