### ISSUE TITLE
TopMovies

### ISSUE THREAD

**Issue by Politecoder** [SaurabhKaperwan/CSX#55]
Bro there are resumable links too in TopMovies site just as Moviesmod, if you can then please add those too.

**Comment by SaurabhKaperwan** [comment]
Give an example for which movie they have resume links

**Comment by SaurabhKaperwan** [comment]
Before making an issue please check properly.

**Comment by SaurabhKaperwan** [comment]
![Screenshot_2024-09-04-17-25-16-61_cfa2fd239c8cded9285432912d0e0818.jpg](https://github.com/user-attachments/assets/c145c82e-6363-4edd-a5f7-217084438c93)

**Comment by Politecoder** [comment]
Oo My bad by the way thanks

**Comment by Politecoder** [comment]
![Screenshot_2024-09-04-17-40-52-353](https://github.com/user-attachments/assets/2687fed7-2b0f-4663-a7bd-32847416ae02)
Can you please tell me are you using any specific DNS or vpn ?

**Comment by SaurabhKaperwan** [comment]
No vpn

**Comment by Politecoder** [comment]
Any DNS in the app or your router ?

**Comment by SaurabhKaperwan** [comment]
No jio sim

**Comment by Politecoder** [comment]
Bro Moviesmod works fine but Topmovies not loading seekable video links, I think it's a plugin issue

**Comment by SaurabhKaperwan** [comment]
Bro how can it be a plugin issue if it is working for me

**Comment by Politecoder** [comment]
Ok, not able to figure out my issue, will see if it starts working

**Comment by Politecoder** [comment]
Bro are resumable links getting loaded in Topmovies ? If getting loaded then please send a screenshot of Animal movie links as resumable links are not getting loaded here..

**Comment by SaurabhKaperwan** [comment]
![Screenshot_2024-09-06-15-33-24-10_cfa2fd239c8cded9285432912d0e0818.jpg](https://github.com/user-attachments/assets/3ca11b17-ca9e-4f06-9c7b-f7d814c85639)

**Comment by SaurabhKaperwan** [comment]
One time try after uninstalling streamplay and uhdm extension

**Comment by Politecoder** [comment]
Bro it's working now, a big thanks!

**Comment by Politecoder** [comment]
Bro there are few suggestions for Moviesmod and Topmovies plugin:
1. It just shows (CF-type 1 1080p) for resumable links, it would be great if they are renamed as 10bit or Bluray as in BollyFlix 
2. Some series such as 'Baahubali:The Crown Of Blood' are not showing up but are present on the site.(Topmovies)

**Comment by SaurabhKaperwan** [comment]
For the baahubali website using a different structure=> not going to fix

**Comment by Politecoder** [comment]
Ok no issues

**Comment by Politecoder** [comment]
Bro, while I try to play this movie (Kalki) in Topmovies, resume links are playing non seekable videos, I think there is some issue in naming the links, or may be something else.
