### ISSUE TITLE
Netflix Mirror issue

### ISSUE THREAD

**Issue by angeldrake668** [SaurabhKaperwan/CSX#58]
Hi, Kindly check the netflixmirror extension. It has stopped working since yesterday.

Thank you for your hard-work and time.

**Comment by SaurabhKaperwan** [comment]
Can't fix they enable human verification

**Comment by SaurabhKaperwan** [comment]
U can use my other extensions

**Comment by angeldrake668** [comment]
Ok, thanks for an update.
