### ISSUE TITLE
Bollyflix not working on Android TV

### ISSUE THREAD

**Issue by karanveers969** [SaurabhKaperwan/CSX#59]
Works great on tablet and phone 
On tv it shows this 
![Uploading IMG_20240906_211327_380.jpg…]()

**Comment by karanveers969** [comment]
![IMG_20240906_211327_380](https://github.com/user-attachments/assets/fb027e86-90c2-4cd3-bf21-69ff5c8906f1)

**Comment by SaurabhKaperwan** [comment]
It means it is not working for that particular show or movie
