### ISSUE TITLE
Worldfree4u

### ISSUE THREAD

**Issue by Krishna-art-dev** [SaurabhKaperwan/CSX#64]
https://world4ufree.boston/download-berlin-2023-hindi-movie/

Idk why this movie subtitle is just big ( not an issue but reported it )
Sendcm 1080p doesn't work (https://world4ufree.boston/download-sector-36-2024-hindi-movie/)
720p works idk why 

Did not able to find sendcm on random other movies so can't test that

**Comment by SaurabhKaperwan** [comment]
Subtitle issue is not related to extension

**Comment by SaurabhKaperwan** [comment]
Sendcm works if u play it in vlc

**Comment by Krishna-art-dev** [comment]
Hmm
