### ISSUE TITLE
Online movie Hindi ( connection timeout)

### ISSUE THREAD

**Issue by Krishna-art-dev** [SaurabhKaperwan/CSX#65]
![Screenshot_2024-09-15-17-00-02-16_cfa2fd239c8cded9285432912d0e0818](https://github.com/user-attachments/assets/fbe9a733-808a-4241-bf58-be4d1843f48f)

**Comment by SaurabhKaperwan** [comment]
They change the domain and I can't  find  new domain.

**Comment by phisher98** [comment]
Website is up now just use Cloudflare Tunnel App
