### ISSUE TITLE
Moviesmod ( no link ) 

### ISSUE THREAD

**Issue by Krishna-art-dev** [SaurabhKaperwan/CSX#66]
![Screenshot_2024-09-15-17-02-39-42_cfa2fd239c8cded9285432912d0e0818](https://github.com/user-attachments/assets/c22cded2-581b-465e-9f45-086893869fcf)
![Screenshot_2024-09-15-17-02-54-49_cfa2fd239c8cded9285432912d0e0818](https://github.com/user-attachments/assets/cfef15e9-a233-4535-bf9c-e8cbc47caa30)

Movies doesn't work 
Webseries work ( no cfworker, just instant download)

**Comment by SaurabhKaperwan** [comment]
Send photo in browser

**Comment by Krishna-art-dev** [comment]
> Send photo in browser

![Uploading Screenshot_2024-09-15-17-09-33-14_e4424258c8b8649f6e67d283a50a2cbc.jpg…]()

**Comment by Krishna-art-dev** [comment]
> Send photo in browser

![Screenshot_2024-09-15-17-09-33-14_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/user-attachments/assets/75226519-45fe-4ead-a763-7a18542b7c32)

**Comment by Krishna-art-dev** [comment]
![Screenshot_2024-09-15-17-10-36-55_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/user-attachments/assets/f6bdd0bf-245b-4ccf-a631-acab2835f9fc)
File exits

**Comment by SaurabhKaperwan** [comment]
Will look into👍

**Comment by Krishna-art-dev** [comment]
> Will look into👍

File name is different? Is that causing problems?

**Comment by SaurabhKaperwan** [comment]
> > Will look into👍
> 
> File name is different? Is that causing problems?

No they change many things

**Comment by Krishna-art-dev** [comment]
> > > Will look into👍
> > 
> > 
> > File name is different? Is that causing problems?
> 
> No they change many things

Yes second movie had same file, still happened to that movie also 
![Screenshot_2024-09-15-17-13-05-55_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/user-attachments/assets/af781aec-f024-420c-9c56-10694f663b7a)

**Comment by SaurabhKaperwan** [comment]
Just check they remove all stream links so can't fix it.

**Comment by Krishna-art-dev** [comment]
> Just check they remove all stream links so can't fix it.

Sad they will add again? Or permanently gone, and there will be only instant, resume worker, resume cloud? 


From where you had known about cfworker link From moviesmod ?

**Comment by SaurabhKaperwan** [comment]
> > Just check they remove all stream links so can't fix it.
> 
> Sad they will add again? Or permanently gone, and there will be only instant, resume worker, resume cloud? 
> 
> 
> From where you had known about cfworker link From moviesmod ?

Don't know
