### ISSUE TITLE
Moviesdrive ( error code 2004 ) 

### ISSUE THREAD

**Issue by Krishna-art-dev** [SaurabhKaperwan/CSX#68]
No movies plays, no anime nothing

**Comment by Krishna-art-dev** [comment]
![Screenshot_2024-09-15-17-21-15-82_cfa2fd239c8cded9285432912d0e0818](https://github.com/user-attachments/assets/c8a176f8-7fec-4da7-92ec-613265029fe0)

**Comment by SaurabhKaperwan** [comment]
Working fine for me

**Comment by Krishna-art-dev** [comment]
> Working fine for me

Let me check

**Comment by Krishna-art-dev** [comment]
> Working fine for me

https://moviesdrive.world/officer-black-belt-2024/
Can you check this movie

**Comment by SaurabhKaperwan** [comment]
> > Working fine for me
> 
> https://moviesdrive.world/officer-black-belt-2024/
> Can you check this movie 

Working fine for this movie

**Comment by Krishna-art-dev** [comment]
> Working fine for me



> > > Working fine for me
> > 
> > 
> > https://moviesdrive.world/officer-black-belt-2024/
> > Can you check this movie
> 
> Working fine for this movie

Let me send screen recording

**Comment by Krishna-art-dev** [comment]
> > > Working fine for me
> > 
> > 
> > https://moviesdrive.world/officer-black-belt-2024/
> > Can you check this movie
> 
> Working fine for this movie

Only pixeldrain source isn't working, hubcloud is working ( before this wasn't working also )

**Comment by SaurabhKaperwan** [comment]
Working fine for me maybe vpn can fix it for u. If it can't fix it then I can't do anything.

**Comment by Krishna-art-dev** [comment]
> Working fine for me maybe vpn can fix it for u. If it can't fix it then I can't do anything.

Okyy
