### ISSUE TITLE
Gdindex ( movie not loading)

### ISSUE THREAD

**Issue by Krishna-art-dev** [SaurabhKaperwan/CSX#69]
Only homepage load, when tap on a specific movie it doesn't load

**Comment by SaurabhKaperwan** [comment]
It is loading for me

**Comment by SaurabhKaperwan** [comment]
> Yesterday it is working for me

**Comment by Krishna-art-dev** [comment]
> > Yesterday it is working for me

Today working for you? I think that's server problem will be fix automatically

**Comment by SaurabhKaperwan** [comment]
Now it is working fine
