### ISSUE TITLE
Full4movie ( issue I can't able to describe so screen recording) 

### ISSUE THREAD

**Issue by Krishna-art-dev** [SaurabhKaperwan/CSX#70]
https://filetransfer.io/data-package/Vo1U2QIq#link

**Comment by Krishna-art-dev** [comment]
52mb recoding size, that's why file transfer

**Comment by Krishna-art-dev** [comment]
Normal people like me will think it's a source error, why this happens idk, large timestamp skip and this happens

**Comment by SaurabhKaperwan** [comment]
Use vpn
