### ISSUE TITLE
0gomovies ( no movie link found ) 

### ISSUE THREAD

**Issue by Krishna-art-dev** [SaurabhKaperwan/CSX#71]

**Comment by SaurabhKaperwan** [comment]
It is returning links but u have to play links in vlc

**Comment by Krishna-art-dev** [comment]
> It is returning links but u have to play links in vlc

Naah it doesn't show any links

**Comment by Krishna-art-dev** [comment]
![Uploading Screenshot_2024-09-15-19-46-36-22_cfa2fd239c8cded9285432912d0e0818.jpg…]()

**Comment by Krishna-art-dev** [comment]
![Screenshot_2024-09-15-19-46-36-22_cfa2fd239c8cded9285432912d0e0818](https://github.com/user-attachments/assets/3f7bf3b6-fb33-4b83-ac6d-b2969f600b7f)

**Comment by Krishna-art-dev** [comment]
![Screenshot_2024-09-15-19-47-26-91_cfa2fd239c8cded9285432912d0e0818](https://github.com/user-attachments/assets/e400d7dd-ebf9-4be4-8a59-7efdb2d444e1)

**Comment by SaurabhKaperwan** [comment]
It is working fine for me
