### ISSUE TITLE
bollyflix and vegamovies stopped working after the plugin update

### ISSUE THREAD

**Issue by AllMustDie** [SaurabhKaperwan/CSX#75]
They are not working anymore. Yesterday it was working fine. Today vegamovies and bollyflix were updated in the background. And after that they stopped working. At least doesn't work on my device

**Comment by SaurabhKaperwan** [comment]
Install extractor extension

**Comment by AllMustDie** [comment]
Hi, could you please share the link or the shortcut of the extension because I couldn't find it in the mega repository

**Comment by SaurabhKaperwan** [comment]
It is in my repo

**Comment by AllMustDie** [comment]
I appreciate your help. It's working fine now. Thank you!
