### ISSUE TITLE
GDindex and Vadapav rework 

### ISSUE THREAD

**Issue by nguyenquocngu93** [SaurabhKaperwan/CSX#79]
Is there any change you put imdb id support to these extensions, because when i watch any movie , the extension always automatically recognizes a movie as a tv series , and then i can't find any subtitle 
![Screenshot_2024-09-22-21-40-59-894_com lagradost cloudstream3 prerelease](https://github.com/user-attachments/assets/48581d14-0ca5-494b-8f51-a33454fa8c2c)

**Comment by SaurabhKaperwan** [comment]
Don't ask about the app issue
