### ISSUE TITLE
Vega plugin issue

### ISSUE THREAD

**Issue by Krishna-art-dev** [SaurabhKaperwan/CSX#84]
![Screenshot_2024-09-24-21-19-13-59_cfa2fd239c8cded9285432912d0e0818](https://github.com/user-attachments/assets/47c9079b-2c79-4124-ad33-47d8ed83bb32)
![Screenshot_2024-09-24-21-22-08-13_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/user-attachments/assets/910e4097-10a9-49db-b75a-5c1851bbce81)
Coming soon, but movie is available in site, thinking because of zip file 

Can you add something that says it's zip file and add download support for it
I use vega to download movies, directly using play in browser

**Comment by SaurabhKaperwan** [comment]
Not going to do it
