### ISSUE TITLE
Prime Video Mirror

### ISSUE THREAD

**Issue by Politecoder** [SaurabhKaperwan/CSX#85]
Prime Video Mirror has also been added on Netflix mirror website which you have already added please add this also (you can wait until they give series support)
![Screenshot_2024-09-24-23-27-15-644](https://github.com/user-attachments/assets/d64396c6-31be-45b5-9e92-24e7df749213)
![Screenshot_2024-09-24-23-27-24-737](https://github.com/user-attachments/assets/e21de25f-8af0-4dfa-aa73-3a8d32155d03)

**Comment by SaurabhKaperwan** [comment]
Will work on it.

**Comment by Politecoder** [comment]
Thanks bro

**Comment by Politecoder** [comment]
But names are not being displayed below the images I think it's a issue
![Screenshot_2024-09-25-13-17-26-034](https://github.com/user-attachments/assets/8423d98f-3a36-402b-8835-12428d675e1d)

**Comment by SaurabhKaperwan** [comment]
Before making an issue first check the website if the website doesn't show the title then how I'm gonna add it.

**Comment by Politecoder** [comment]
Ok my bad, will take care
