### ISSUE TITLE
Site request (movie#flix)

### ISSUE THREAD

**Issue by Krishna-art-dev** [SaurabhKaperwan/CSX#87]
Site link = https://themoviezflix.cn.com/

Site like moviesmod, with different servers

Pros 
- lots of severs
- streaming sources 
- direct download source 
- 1080p mkv support 
- gdtot link And main download ( there own download type you can check )

Cons 
- first page have 18+
- sometimes Streaming source doesn't have sources ( expectations vidhide and voe )

**Comment by SaurabhKaperwan** [comment]
Gdot has cloudflare protection and the main download link is the download only link.

**Comment by SaurabhKaperwan** [comment]
Chances are rare that I will add it.

**Comment by Krishna-art-dev** [comment]
No problem, plugin that we already have, am happy with that 

Just share that website because site was like moviesmod

**Comment by SonaliBendre** [comment]
> Site like moviesm

PR in cloudstream app to support webview for cloudflare bypass like tachiyomi
