### ISSUE TITLE
Refinement(NF mirror)

### ISSUE THREAD

**Issue by Politecoder** [SaurabhKaperwan/CSX#89]
Bro can you please add age rating also that's present on the site to both Netflix and Amazon prime..
Thanks

**Comment by SaurabhKaperwan** [comment]
Already added

**Comment by Politecoder** [comment]
> How as a tag

Yes it will be fine

**Comment by SaurabhKaperwan** [comment]
Will do this in the next update when they add a series of prime video

**Comment by Politecoder** [comment]
Sure bro

**Comment by Politecoder** [comment]
Bro they added series support in prime video mirror

**Comment by Politecoder** [comment]
Thanks
