### ISSUE TITLE
Site not working 

### ISSUE THREAD

**Issue by Chani-rajat** [SaurabhKaperwan/CSX#9]
Hey provider, Cinevez Hdhub4u and Vega movies repos' aren't working and there is no AUDIO in Full4movies.

**Comment by SaurabhKaperwan** [comment]
Cinevez is working fine for me. Vegamovies raised cloudflare protection and hdhub it is in testing and for full4movies audio issue select link with unknown quality

**Comment by Chani-rajat** [comment]
Bro can u add Multimovies 
http://multimovies.icu/

**Comment by SaurabhKaperwan** [comment]
Already added in phiser repo

**Comment by Chani-rajat** [comment]
Phiser ?

**Comment by SaurabhKaperwan** [comment]
HindiProviders : 
 https://raw.githubusercontent.com/phisher98/HindiProviders/builds/HindiProviders.json

**Comment by Chani-rajat** [comment]
Where to check more providers. 
On Cloudstream GitHub page, this repo is not showing. 
Thanks for you support🫡
