### ISSUE TITLE
No Anime website present 

### ISSUE THREAD

**Issue by Windman99** [SaurabhKaperwan/CSX#90]
Hello sir can You add anime website on Your repository any one of it
https://yugenanime.tv/

**Comment by SaurabhKaperwan** [comment]
Yugenanime already present in hexated repo

**Comment by Windman99** [comment]
Can You add a anime website specially for Your repo because you are updating Your repos and hexated dont update their repos anymore 
Please add this on your https://www.miruro.tv its a best one

**Comment by SaurabhKaperwan** [comment]
This website is already added in streamplay.

**Comment by SaurabhKaperwan** [comment]
And I don't like this website

**Comment by Windman99** [comment]
Any other anime website you like example 
https://animesugetv.to
