### ISSUE TITLE
Topmovies

### ISSUE THREAD

**Issue by Politecoder** [SaurabhKaperwan/CSX#92]
It's not extracting resumable links but are working fine on the website, movies mod is working fine.
Thanks

**Comment by SaurabhKaperwan** [comment]
Show example

**Comment by Politecoder** [comment]
![Screenshot_2024-10-04-11-52-15-076](https://github.com/user-attachments/assets/09b4a6b7-b1f6-4eba-90cb-a27242bb6182)
![Screenshot_2024-10-04-11-51-02-640](https://github.com/user-attachments/assets/93b69200-2c98-494d-9238-62936fe29e42)
