### ISSUE TITLE
Anichi

### ISSUE THREAD

**Issue by Rachitidk** [SaurabhKaperwan/CSX#93]
Can you fix and import anichi from rowdycado and add to your repo, as they they no longer maintain it, so had stopped working.

**Comment by SaurabhKaperwan** [comment]
It is already maintained in streamplay extension

**Comment by Rachitidk** [comment]
> It is already maintained in streamplay extension

Ik that, but there are many problems, such as
1) ova, ona not supported
2) wrong episode, season for many episode, eg aot season 4, promised Neverland.
3) no link found for many anime eg re:zero after season 1 due to wrong arrangement in tmdb.
4) etc. Can recall right now.
@SaurabhKaperwan
