### ISSUE TITLE
Anichi

### ISSUE THREAD

**Issue by Rachitidk** [SaurabhKaperwan/CSX#94]
https://github.com/SaurabhKaperwan/CSX/issues/93#issuecomment-2395534899

**Comment by SaurabhKaperwan** [comment]
I'm not doing it.

**Comment by Rachitidk** [comment]
> I'm not doing it.

Np, you could have replied in that comment, I thought u didn't saw so open a new issue.

**Comment by Rachitidk** [comment]
Do you know how to delete the issue fully from my side or can you do it, then please do.
