### ISSUE TITLE
Site Request 

### ISSUE THREAD

**Issue by sakib2k23** [SaurabhKaperwan/CSX#95]
For anime kayoanime update the video quality when they get Blu-ray 
https://kayoanime.com/
> 

Cinedoze is a Bollywood site but they provide the WWE wrestling matches so much quickly 
https://cinedoze.com/

I hope you will add 🥹🥹

**Comment by rockhero1234** [comment]
Links are protected in cinedoze

**Comment by sakib2k23** [comment]
> Links are protected in cinedoze

But there are so many web that SaurabhKaperwan extracted

**Comment by sakib2k23** [comment]
> Not possible in this case

So kayoanime?
Could you do that

**Comment by rockhero1234** [comment]
Does it has enough content to add

**Comment by SaurabhKaperwan** [comment]
> > Links are protected in cinedoze
> 
> But there are so many web that SaurabhKaperwan extracted

If I try I can bypass it but this website is using hubcloud servers and I already added multiple websites that use hubcloud. So it is no from my side right now.

**Comment by rockhero1234** [comment]
How will you do so?

**Comment by rockhero1234** [comment]
Update: got the way to bypass I will add this

**Comment by sakib2k23** [comment]
> Does it has enough content to add

Yes and most important thing is when the blu-ray releases they updated the series

**Comment by rockhero1234** [comment]
> > > Links are protected in cinedoze
> > 
> > 
> > But there are so many web that SaurabhKaperwan extracted
> 
> If I try I can bypass it but this website is using hubcloud servers and I already added multiple websites that use hubcloud. So it is no from my side right now.

I tried a scrape there is a post request in form in protected link. I called that using python isnis working but in kotlin returning normal. Do you know what is happening

**Comment by SaurabhKaperwan** [comment]
Pass cookies and headers

**Comment by rockhero1234** [comment]
> For anime kayoanime update the video quality when they get Blu-ray https://kayoanime.com/
> 
> > 
> 
> Cinedoze is a Bollywood site but they provide the WWE wrestling matches so much quickly https://cinedoze.com/
> 
> I hope you will add 🥹🥹
Test Cinedoze if it works for you 
CSX(Hindi & English) testing : 
 https://raw.githubusercontent.com/rockhero1234/CSX/refs/heads/builds/CS.json

**Comment by SaurabhKaperwan** [comment]
> > For anime kayoanime update the video quality when they get Blu-ray https://kayoanime.com/
> > 
> > > 
> > 
> > Cinedoze is a Bollywood site but they provide the WWE wrestling matches so much quickly https://cinedoze.com/
> > 
> > I hope you will add 🥹🥹
> Test Cinedoze if it works for you 
> CSX(Hindi & English) testing : 
>  https://raw.githubusercontent.com/rockhero1234/CSX/refs/heads/builds/CS.json
> 

See your pr I already write comments their

**Comment by sakib2k23** [comment]
> > > For anime kayoanime update the video quality when they get Blu-ray https://kayoanime.com/
> > > > 
> > > 
> > > 
> > > Cinedoze is a Bollywood site but they provide the WWE wrestling matches so much quickly https://cinedoze.com/
> > > I hope you will add 🥹🥹
> > > Test Cinedoze if it works for you
> > > CSX(Hindi & English) testing :
> > > https://raw.githubusercontent.com/rockhero1234/CSX/refs/heads/builds/CS.json
> 
> See your pr I already write comments there

Thank u so much bro working 
Love your work
Can you plz add the kayoanime also🥹🥹

**Comment by rockhero1234** [comment]
Kayoanime have google drive folder not video link that will be little complicated to do so to use drive api and so.

**Comment by sakib2k23** [comment]
> Kayoanime have google drive folder not video link that will be little complicated to do so to use drive api and so.

https://github.com/recloudstream/cloudstream/blob/master/library%2Fsrc%2FcommonMain%2Fkotlin%2Fcom%2Flagradost%2Fcloudstream3%2Fextractors%2FGdriveplayer.kt

Google drive player extractor

**Comment by rockhero1234** [comment]
That's what I said if you had links of gdrive for video we can extract but they had folders

**Comment by sakib2k23** [comment]
> That's what I said if they had links of gdrive for video we can extract but they had folders

Ooo ok thanks bro
